/**
 * Writer Agent Example Usage
 * Demonstrates how to use the Writer Agent to generate landing page content
 */

import { WriterAgent } from './index';
import { ArchitectBrief } from '../../types/architect-brief';
import { NicheInput } from '../../types/niche';

// Example: Generate landing page for dental clinic
async function exampleDentalClinic() {
  console.log('=== Writer Agent Example: Dental Clinic ===\n');

  // Sample Architect Brief (normally generated by ArchitectAgent)
  const nicheInput: NicheInput = {
    professionalSingular: 'Stomatolog',
    professionalPlural: 'Stomatologi',
    businessEntity: 'Cabinet Stomatologic',
    businessEntitySlug: 'cabinet-stomatologic',
    endClient: 'Pacienți cu probleme dentare',
    primaryPainPoint: 'Scaun gol și programări ratate',
    technicalBenefit: 'Programări online și vizibilitate pe Google Maps',
    relatedNiches: ['cabinet-veterinar', 'clinica-oftalmologie', 'cabinet-medical'],
  };

  const architectBrief: ArchitectBrief = {
    niche: nicheInput,
    lsiKeywords: [
      'implant dentar',
      'albire profesională',
      'detartraj ultrasonic',
      'coroană dentară',
      'aparat dentar invizibil',
      'ortodonție',
      'chirurgie orală',
      'periodontologie',
      'endodonție',
      'protetică dentară',
      'igienă dentară',
      'programare online stomatologie',
      'cabinet stomatologic modern',
      'tehnologie dentară',
      'consultație stomatologică',
    ],
    hookAngle:
      '80% din cabinetele stomatologice pierd minimum 15 pacienți pe lună din cauza unui site care nu răspunde pe mobile.',
    skepticalObjections: [
      'Deja am site și pagină de Facebook, pacienții vin oricum prin recomandări',
      'Nu am timp să mă ocup de un site nou, sunt ocupat cu pacienții',
      'Am încercat deja marketing online și nu a funcționat',
      'Este prea scump, mai bine investesc în echipamente',
      'Nu știu cum funcționează tehnologia, nu sunt specialist',
    ],
    contentOutline: {
      hero: 'Lead with mobile-first pain point and transformation promise',
      aioStrategy: 'Define what modern dental site needs: speed, schema, mobile, booking',
      painAgitation:
        'Calculate lost revenue from missed calls, slow site, no online booking. Use concrete RON numbers.',
      comparisonTable:
        'Show generic agency (template, slow, no results) vs Webnova (custom, fast, ROI-driven)',
      technicalSolution:
        'Translate Core Web Vitals, Schema markup, mobile-first into patient acquisition features',
      faq: 'Address each objection with validation + reversal + proof + action',
      cta: 'Emotional urgency around lost patients today, easy first step (free audit)',
    },
    generatedAt: new Date(),
  };

  // Initialize Writer Agent in mock mode (no API calls)
  const writer = new WriterAgent({
    language: 'ro',
    mockMode: true, // Set to false to use real API
    minWordCount: 1500,
    danKennedyStyle: true,
  });

  try {
    // Test connection
    console.log('Testing AI service connection...');
    const connected = await writer.testConnection();
    console.log(`Connection status: ${connected ? 'OK' : 'FAILED'}\n`);

    if (!connected) {
      console.error('Failed to connect to AI service');
      return;
    }

    // Generate landing page
    console.log('Generating landing page content...\n');
    const landingPage = await writer.write(architectBrief);

    // Display results
    console.log('\n=== GENERATED LANDING PAGE ===\n');
    console.log(`Slug: ${landingPage.slug}`);
    console.log(`Meta Title: ${landingPage.metaTitle}`);
    console.log(`Meta Description: ${landingPage.metaDescription}\n`);

    console.log('=== HERO SECTION ===');
    console.log(`H1: ${landingPage.heroSection.h1}`);
    console.log(`Subheadline: ${landingPage.heroSection.subheadline}\n`);

    console.log('=== AIO DEFINITION ===');
    console.log(landingPage.aioDefinition.substring(0, 200) + '...\n');

    console.log('=== PAIN AGITATION ===');
    console.log(landingPage.painAgitation.substring(0, 200) + '...\n');

    console.log('=== COMPARISON TABLE ===');
    console.log(`Headers: ${landingPage.comparisonTable.headers.join(' | ')}`);
    console.log(`Rows: ${landingPage.comparisonTable.rows.length}\n`);

    console.log('=== TECHNICAL SOLUTION ===');
    console.log(landingPage.technicalSolution.substring(0, 200) + '...\n');

    console.log('=== FAQ SECTION ===');
    landingPage.faqSection.forEach((item, i) => {
      console.log(`Q${i + 1}: ${item.question}`);
      console.log(`A${i + 1}: ${item.answer.substring(0, 100)}...`);
      console.log();
    });

    console.log('=== CALL TO ACTION ===');
    console.log(`Headline: ${landingPage.callToAction.headline}`);
    console.log(`Button: ${landingPage.callToAction.buttonText}`);
    console.log(`Body: ${landingPage.callToAction.body.substring(0, 150)}...\n`);

    console.log('=== INTERNAL LINKS ===');
    landingPage.internalLinks.forEach((link) => {
      console.log(`- [${link.text}](/${link.slug})`);
    });
    console.log();

    // Export to JSON
    const jsonOutput = writer.exportLandingPage(landingPage);
    console.log('\n=== JSON OUTPUT (first 500 chars) ===');
    console.log(jsonOutput.substring(0, 500) + '...\n');

    console.log('=== EXAMPLE COMPLETE ===');
  } catch (error) {
    console.error('Error generating landing page:', error);
    throw error;
  }
}

// Run the example if this file is executed directly
if (require.main === module) {
  exampleDentalClinic()
    .then(() => {
      console.log('\nExample completed successfully!');
      process.exit(0);
    })
    .catch((error) => {
      console.error('\nExample failed:', error);
      process.exit(1);
    });
}

export { exampleDentalClinic };
