import { NicheInput } from './niche';

/**
 * Content Outline Structure
 *
 * Defines section-specific notes and strategies for content generation
 */
export interface ContentOutline {
  /**
   * Hero section strategy notes
   */
  hero: string;

  /**
   * AI Overview optimization notes
   */
  aioStrategy: string;

  /**
   * Pain agitation approach notes
   */
  painAgitation: string;

  /**
   * Comparison table strategy
   */
  comparisonTable: string;

  /**
   * Technical solution presentation notes
   */
  technicalSolution: string;

  /**
   * FAQ strategy and focus areas
   */
  faq: string;

  /**
   * Call-to-action strategy
   */
  cta: string;
}

/**
 * Architect Agent Output Interface
 *
 * Represents the strategic brief generated by the Architect agent.
 * This brief guides the Writer agent in creating persuasive, industry-specific content.
 */
export interface ArchitectBrief {
  /**
   * Reference to the original niche input data
   */
  niche: NicheInput;

  /**
   * Latent Semantic Indexing keywords - Industry-specific terminology
   * These enhance SEO relevance and demonstrate domain expertise
   * Example: ["profilaxie dentară", "detartraj", "consultație stomatologică"]
   */
  lsiKeywords: string[];

  /**
   * Controversial or engaging opening statement
   * Used to capture attention and establish credibility
   * Example: "80% din cabinetele stomatologice pierd clienți pentru că nu apar pe Google Maps"
   */
  hookAngle: string;

  /**
   * Array of 5 specific skeptical objections from business owners
   * These represent real concerns that need to be addressed in the copy
   * Example: ["E prea scump", "Nu am timp să învăț tehnologie nouă", "Clienții mei nu caută online"]
   */
  skepticalObjections: string[];

  /**
   * Section-by-section content strategy notes
   * Provides guidance for each major section of the landing page
   */
  contentOutline: ContentOutline;

  /**
   * Timestamp when the brief was generated
   */
  generatedAt: Date;
}
